[clickhouse]
hostname = "hostname"
user = "user"
password = "p@s$$w0rd"
db = "db"
port = 8123

[server]
label = "PRG"
interface_filter = ["eth0", "eth1"]
lat = 50.0833
lng = 14.4667
priority = 1
center = true
